export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_CHECK_AUTHENTICATION = 'AUTH_CHECK_AUTHENTICATION';
export const AUTH_HANDLE_AUTHENTICATION = 'AUTH_HANDLE_AUTHENTICATION';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SET_AUTHENTICATED = 'AUTH_SET_AUTHENTICATED';
export const AUTH_SET_USERNAME = 'AUTH_SET_USERNAME';

export const NAMESPACE_CREATE = 'NAMESPACE_CREATE';
export const NAMESPACE_CREATE_CHANGE_INPUT = 'NAMESPACE_CREATE_CHANGE_INPUT';
export const NAMESPACE_CREATE_ERROR = 'NAMESPACE_CREATE_ERROR';
export const NAMESPACE_DELETE = 'NAMESPACE_DELETE';
export const NAMESPACE_DELETE_CHECK_WATCH = 'NAMESPACE_DELETE_CHECK_WATCH';
export const NAMESPACE_DELETE_ERROR = 'NAMESPACE_DELETE_ERROR';
export const NAMESPACE_DELETE_START_WATCH = 'NAMESPACE_DELETE_START_WATCH';
export const NAMESPACE_DELETE_STOP_WATCH = 'NAMESPACE_DELETE_STOP_WATCH';
export const NAMESPACE_LIST = 'NAMESPACE_LIST';
export const NAMESPACE_LIST_ERROR = 'NAMESPACE_LIST_ERROR';
export const NAMESPACE_LIST_SUCCESS = 'NAMESPACE_LIST_SUCCESS';
export const NAMESPACE_SELECT = 'NAMESPACE_SELECT';
export const NAMESPACE_WATCH_FOR_DELETION = 'NAMESPACE_WATCH_FOR_DELETION';

export const ROLE_CREATE = 'ROLE_CREATE';
export const ROLE_CREATE_ERROR = 'ROLE_CREATE_ERROR';
export const ROLE_GET = 'ROLE_GET';
export const ROLE_GET_ERROR = 'ROLE_GET_ERROR';

export const ROLEBINDING_CREATE = 'ROLEBINDING_CREATE';
export const ROLEBINDING_CREATE_CHANGE_INPUT = 'ROLEBINDING_CREATE_CHANGE_INPUT';
export const ROLEBINDING_CREATE_ERROR = 'ROLEBINDING_CREATE_ERROR';
export const ROLEBINDING_DELETE = 'ROLEBINDING_DELETE';
export const ROLEBINDING_DELETE_CHECK_WATCH = 'ROLEBINDING_DELETE_CHECK_WATCH';
export const ROLEBINDING_DELETE_ERROR = 'ROLEBINDING_DELETE_ERROR';
export const ROLEBINDING_DELETE_START_WATCH = 'ROLEBINDING_DELETE_START_WATCH';
export const ROLEBINDING_DELETE_STOP_WATCH = 'ROLEBINDING_DELETE_STOP_WATCH';
export const ROLEBINDING_LIST = 'ROLEBINDING_LIST';
export const ROLEBINDING_LIST_ERROR = 'ROLEBINDING_LIST_ERROR';
export const ROLEBINDING_LIST_SUCCESS = 'ROLEBINDING_LIST_SUCCESS';
