export const CONFIG_SET = 'CONFIG_SET';
export const NAMESPACE_CREATE_CHANGE_INPUT = 'NAMESPACE_CREATE_CHANGE_INPUT';
export const NAMESPACE_DELETE_CHANGE_INPUT = 'NAMESPACE_DELETE_CHANGE_INPUT';
export const NAMESPACE_LIST = 'NAMESPACE_LIST';
export const ROLEBINDING_LIST = 'ROLEBINDING_LIST';
